name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_name:
          - tests::tests::test_add_book
          - tests::tests::test_add_max_capacity
          - tests::tests::test_display_books
          - tests::tests::test_get_index
          - tests::tests::test_non_existing_book
          - tests::tests::test_sell_book
          - tests::tests::test_sell_book_2
          - tests::tests::test_invalid_json_file
          - tests::tests::test_invalid_json_file_2
          - tests::tests::test_update_book
          - tests::tests::test_remove_book
          - tests::tests::test_sell_more_than_available
          - tests::tests::test_sell_more_than_available_2

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #V.4.1.1
    - name: Install nextest
      run: cargo install cargo-nextest --locked
    - name: Run ${{ matrix.test_name }} test
      run: cargo nextest run ${{ matrix.test_name }} --verbose
