name: Rust

on:
  workflow_dispatch:
  push:

jobs:
  compare_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #V.4.1.1
        with:
          fetch-depth: 0

      - name: Find path (modify)
        run: |
              last_commit=$(git log -1 --pretty=format:"%h")
              full_path=$(git diff-tree --no-commit-id --name-only -r ${last_commit})
              changes_path=$(dirname "$full_path" | awk -F'/' '{print $1"/"$2}')
              package_types=("package.json" "Cargo.toml")
              package=""
          
              for dir_path in ${changes_path}; do
                  echo $dir_path 
                  temp=$(echo "$dir_path" | awk -F'/' '{print $1}')
                  echo $temp
                  case $temp in
                      "packages" )
                          full_path=$changes_path
                          ;;
                      *)
                          continue
                          ;;
                  esac                
              done
              
              cd $dir_path
              
              files=$(ls)
              
              for package_type in ${package_types[@]}; do
                      for file in ${files[@]}; do
                      if [ "${package_type}" == "${file}" ]; then
                          package=${package_type}
                          echo $package
                      fi
                      done    
              done
              full_path_with_package="${full_path}/${package}"
              echo "FULL_PATH=$full_path_with_package" >> $GITHUB_ENV

      - name: Version verification
        id: check
        uses: EndBug/version-check@53c9309fefac91a21f852d5ca69f33878280d2f5
        with:
          file-name: ${{ env.FULL_PATH }}
      - name: Log when changed
        run: |
            echo "${{ steps.check.outputs.commit }}" 
            echo "${{ steps.check.outputs.type }}"
            echo "${{ steps.check.outputs.changed }}" 
            echo "${{ steps.check.outputs.version }}"
      