name: Publish Packages

on: push

jobs:
  check_version_change:
    runs-on: ubuntu-latest
    outputs:
      CHANGED: ${{steps.check_version.outputs.changed}}
      VERSION: ${{steps.check_version.outputs.version}}
      PATH: ${{steps.set_path.outputs.changed_package_path}}
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set Path
        id: set_path
        run: |
          # Get the paths of changed files
          changes_paths=$(git diff-tree --no-commit-id --name-only -r "${{ github.sha }}" | awk -F'/' '{print $1"/"$2}')

          # Manifest names list
          manifest_names=("package.json")

          # Save the manifest path of the changed package in GitHub env and exit without error
          for path in ${changes_paths}; do
            if [[ $path == packages/* ]]; then
              for manifest in "${manifest_names[@]}"; do
                if [[ -f $path/$manifest ]]; then
                  echo "changed_package_path=${path}/${manifest}" >> "$GITHUB_OUTPUT"
                  echo "package_changed=true" >> "$GITHUB_OUTPUT"
                  exit 0
                fi
              done
            fi
          done

          # If we haven't exited yet, no package was changed
          echo "No package was changed in this commit!"
          echo "package_changed=false" >> "$GITHUB_OUTPUT"

      - name: Check Version
        id: check_version
        if: ${{ steps.set_path.outputs.package_changed == 'true' }}
        uses: EndBug/version-check@53c9309fefac91a21f852d5ca69f33878280d2f5
        with:
          file-name: ${{ steps.set_path.outputs.changed_package_path }}

  publish_node:
    runs-on: ubuntu-latest
    needs: check_version_change
    if: ${{needs.check_version_change.outputs.CHANGED == 'true'}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4 #v4.0.2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      - name: Publish
        run: |
          cd "$(echo '${{ needs.check_version_change.outputs.PATH}}' | awk -F'/' '{print $1"/"$2}')"
          npm ci
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}